import type { Metadata } from "next";
import { SideBar, MainContent } from "my-comp-organisms";
import { poppins } from "my-styles/fonts";
import "my-styles/globals.css";
import RightContent from "../components/Organisms/RightContent";

export const metadata: Metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="fixed inset-0 flex w-full">
          <SideBar />
          <MainContent>{children}</MainContent>
          <RightContent />
        </div>
      </body>
    </html>
  );
}
