import 'my-styles/globals.css';
import type { Metadata } from "next";
import { SideBar, MainContent } from "my-comp-organisms";
import RightContent from "../components/Organisms/RightContent";
import style from "./style.module.css";

export const metadata: Metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={style.layout}>
          <SideBar />
          <MainContent>{children}</MainContent>
          <RightContent />
        </div>
      </body>
    </html>
  );
}
